title: Izabelė Jonušaitė
tagline:
logo: /assets/img/logo.png
description: PhD Student in Brain and Cognitive Sciences at MIT
Yoshow_downloads: true
google_analytics: G-JDRE8RCM3B
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
