title: Izabelė Jonušaitė
tagline:
logo: /assets/img/logo.png
description: MSc Cognitive Science student at University of Amsterdam
Yoshow_downloads: true
google_analytics: G-JDRE8RCM3B
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
